#!/usr/bin/env python3
"""
Thin database adapter so the CK PIN pipeline runs on SQLite (local dev) and
PostgreSQL (VPS production) from one codebase.

    from ckdb import connect
    db = connect("sqlite:///out/ck_pincode.db")
    db = connect("postgresql://ck:pw@localhost:5432/ck_pincode")
    db = connect()            # reads $CK_DB_URL, falls back to local sqlite

Design notes
  * SQL is written once in SQLite dialect using '?' placeholders. Postgres
    translation is mechanical and lives in _pg_ddl() / _qmark_to_pyformat().
  * Both engines support `ON CONFLICT ... DO UPDATE`, so every write in the
    pipeline is an idempotent upsert. Nothing is ever dropped or wiped.
  * REAL must become DOUBLE PRECISION on Postgres: pg REAL is float4 (~7
    significant digits) which silently rounds a latitude like 28.567058.
"""
import os
import re

DEFAULT_URL = "sqlite:///out/ck_pincode.db"


def load_env(path=None):
    """Read .env into the environment, the way docker-compose already does.

    Without this, `python serve.py` and `python refresh.py` run with no
    DATA_GOV_KEY even though it sits in .env - the file is a compose feature,
    not a Python one - and the refresh fails with "set DATA_GOV_KEY" while the
    key is plainly there. Real environment variables win, so nothing set by
    compose or the shell is ever overridden.
    """
    path = path or os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    if not os.path.exists(path):
        return 0
    n = 0
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, _, v = line.partition("=")
                k, v = k.strip(), v.strip().strip('"').strip("'")
                if k and k not in os.environ:
                    os.environ[k] = v
                    n += 1
    except OSError:
        return 0
    return n


load_env()      # every entry point imports ckdb, so this runs once, early


# --------------------------------------------------------------- translation
def _qmark_to_pyformat(sql):
    """'?' -> '%s' for psycopg.

    A '?' inside a single-quoted SQL string literal is data and is left alone.
    A literal '%' is escaped to '%%' EVERYWHERE, including inside string
    literals: psycopg scans the whole query for placeholders whenever a params
    sequence is passed, so an unescaped `LIKE 'x%'` raises IndexError. DB.execute
    always passes a tuple (never None) so the unescaping is symmetric.
    """
    out, in_str, i = [], False, 0
    while i < len(sql):
        c = sql[i]
        if c == "'":
            # '' inside a string literal is an escaped quote, not a terminator
            if in_str and i + 1 < len(sql) and sql[i + 1] == "'":
                out.append("''")
                i += 2
                continue
            in_str = not in_str
            out.append(c)
        elif c == "%":
            out.append("%%")
        elif c == "?" and not in_str:
            out.append("%s")
        else:
            out.append(c)
        i += 1
    return "".join(out)


def _split_comment(line):
    """Split a line into (code, comment) on the first '--' that is not inside a
    single-quoted literal."""
    in_str = False
    for i in range(len(line) - 1):
        c = line[i]
        if c == "'":
            in_str = not in_str
        elif c == "-" and line[i + 1] == "-" and not in_str:
            return line[:i], line[i:]
    return line, ""


def _pg_ddl(sql):
    """Translate the canonical SQLite schema into PostgreSQL DDL.

    Rewrites are applied to code only, never to trailing '--' comments: the
    schema contains prose like '>1 is rare but real', and a blind \\bREAL\\b
    substitution turned that into 'but DOUBLE PRECISION'.
    """
    def fix(code):
        # rowid autoincrement -> identity column
        code = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
                      "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                      code, flags=re.I)
        # pg REAL is float4 (~7 significant digits) and would round a latitude
        code = re.sub(r"\bREAL\b", "DOUBLE PRECISION", code, flags=re.I)
        # pg has no CREATE VIEW IF NOT EXISTS; SQLite has no CREATE OR REPLACE VIEW
        code = re.sub(r"\bCREATE\s+VIEW\s+IF\s+NOT\s+EXISTS\b",
                      "CREATE OR REPLACE VIEW", code, flags=re.I)
        return code

    out = []
    for line in sql.splitlines():
        code, comment = _split_comment(line)
        out.append(fix(code) + comment)
    sql = "\n".join(out)
    # PRAGMAs are SQLite-only session settings
    return re.sub(r"^\s*PRAGMA[^;]*;\s*$", "", sql, flags=re.M | re.I)


def split_statements(sql):
    """Split a DDL script into executable statements.

    Splits on semicolons that are outside both string literals and '--' line
    comments, and drops fragments that are only comments/whitespace. The comment
    handling is essential, not cosmetic: schema.sql documents columns with
    prose like `-- 'datagov_directory', 'lgd_villages', ...`, and treating those
    apostrophes as string delimiters desynchronises the quote state for the rest
    of the file (14 statements collapsed into 3).
    """
    stmts, buf, in_str, in_cmt = [], [], False, False
    i = 0
    while i < len(sql):
        c = sql[i]
        if in_cmt:
            buf.append(c)
            if c == "\n":
                in_cmt = False
            i += 1
            continue
        if c == "'":
            if in_str and i + 1 < len(sql) and sql[i + 1] == "'":
                buf.append("''")
                i += 2
                continue
            in_str = not in_str
            buf.append(c)
        elif c == "-" and not in_str and i + 1 < len(sql) and sql[i + 1] == "-":
            in_cmt = True
            buf.append("--")
            i += 2
            continue
        elif c == ";" and not in_str:
            _push(stmts, buf)
            buf = []
        else:
            buf.append(c)
        i += 1
    _push(stmts, buf)
    return stmts


def _push(stmts, buf):
    """Append a statement, ignoring fragments that carry no executable SQL."""
    raw = "".join(buf).strip()
    if not raw:
        return
    code = "\n".join(_split_comment(l)[0] for l in raw.splitlines()).strip()
    if code:
        stmts.append(raw)


# ---------------------------------------------------------------- connection
class DB:
    def __init__(self, conn, dialect):
        self.conn = conn
        self.dialect = dialect          # 'sqlite' | 'postgres'
        self.is_pg = dialect == "postgres"

    # -- statement helpers ---------------------------------------------------
    def _sql(self, sql):
        return _qmark_to_pyformat(sql) if self.is_pg else sql

    def execute(self, sql, params=()):
        cur = self.conn.cursor()
        cur.execute(self._sql(sql), tuple(params))
        return cur

    def executemany(self, sql, seq):
        seq = [tuple(x) for x in seq]
        if not seq:
            return None
        cur = self.conn.cursor()
        cur.executemany(self._sql(sql), seq)
        return cur

    def executescript(self, sql):
        """Run a DDL script. Idempotent: every statement is CREATE ... IF NOT EXISTS."""
        if self.is_pg:
            sql = _pg_ddl(sql)
            cur = self.conn.cursor()
            for stmt in split_statements(sql):
                cur.execute(stmt)
        else:
            self.conn.executescript(sql)
        self.commit()

    # -- reads ---------------------------------------------------------------
    def rows(self, sql, params=()):
        """All rows as dicts, engine-independent."""
        cur = self.execute(sql, params)
        cols = [d[0] for d in cur.description]
        return [dict(zip(cols, r)) for r in cur.fetchall()]

    def q(self, sql, params=()):
        """First column of the first row (counts, scalars)."""
        r = self.execute(sql, params).fetchone()
        return None if r is None else r[0]

    def insert_returning_id(self, sql, params, pk):
        """INSERT ... and return the generated primary key on both engines."""
        if self.is_pg:
            return self.execute(sql + f" RETURNING {pk}", params).fetchone()[0]
        return self.execute(sql, params).lastrowid

    def columns(self, table):
        """Column names for a table. Used by loaders to migrate an existing
        database in place instead of only working on a fresh one."""
        if self.is_pg:
            return [r[0] for r in self.execute(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_name = ?", (table,)).fetchall()]
        # PRAGMA takes no bound parameters; table names here are internal literals
        return [r[1] for r in self.execute(f"PRAGMA table_info({table})").fetchall()]

    def table_exists(self, name):
        if self.is_pg:
            return bool(self.q("SELECT to_regclass(?) IS NOT NULL", (name,)))
        return bool(self.q("SELECT COUNT(*) FROM sqlite_master "
                           "WHERE type='table' AND name=?", (name,)))

    # -- lifecycle -----------------------------------------------------------
    def commit(self):
        self.conn.commit()

    def rollback(self):
        self.conn.rollback()

    def close(self):
        self.conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, *_):
        if exc_type:
            self.rollback()
        else:
            self.commit()
        self.close()


def pg_url_problem(url):
    """Return a human-readable explanation if a Postgres URL is malformed.

    The failure this exists for: `openssl rand -base64 32` emits the base64
    alphabet, which includes '/'. Interpolated raw into a connection URL, that
    '/' ends the authority section, so

        postgresql://ck:R7x/Qm2Z+aB9c=@db:5432/ck_pincode

    parses as host='ck', port='R7x', and libpq fails with the thoroughly
    unhelpful "Servname not supported for ai_socktype". Catch it here and say
    what actually went wrong.
    """
    _, _, rest = url.partition("://")
    if not rest:
        return None                       # bare URL: libpq reads PG* env vars
    authority = rest.split("/", 1)[0]
    if "@" in rest and "@" not in authority:
        return ("the database password contains an unencoded '/', which ends the "
                "URL authority - libpq then treats part of the password as the "
                "hostname.\n"
                "    Fix (preferred): drop the password from CK_DB_URL and set "
                "PGHOST/PGPORT/PGUSER/PGPASSWORD/PGDATABASE instead;\n"
                "    CK_DB_URL=postgresql:// on its own is valid and libpq fills "
                "in the rest.\n"
                "    Or: percent-encode it - '/'->%2F, '@'->%40, ':'->%3A, "
                "'+'->%2B, '#'->%23.\n"
                "    Or: regenerate a URL-safe password: openssl rand -hex 32")
    if authority:
        hostport = authority.rsplit("@", 1)[-1]
        if ":" in hostport:
            port = hostport.rsplit(":", 1)[1]
            if port and not port.isdigit():
                return (f"the port in CK_DB_URL is {port!r}, which is not a number. "
                        "This usually means an unencoded character in the password "
                        "shifted the URL apart. See the encoding note above, or set "
                        "PGHOST/PGUSER/PGPASSWORD/PGDATABASE and use a bare "
                        "CK_DB_URL=postgresql://")
    return None


def pg_url(host, db, user, password, port=5432):
    """Build a Postgres URL with every component correctly percent-encoded."""
    from urllib.parse import quote
    return (f"postgresql://{quote(user, safe='')}:{quote(password, safe='')}"
            f"@{host}:{port}/{quote(db, safe='')}")


def connect(url=None):
    url = url or os.environ.get("CK_DB_URL") or DEFAULT_URL

    if url.startswith("sqlite://"):
        import sqlite3
        path = url[len("sqlite:///"):] if url.startswith("sqlite:///") else url[len("sqlite://"):]
        d = os.path.dirname(os.path.abspath(path))
        if d:
            os.makedirs(d, exist_ok=True)
        conn = sqlite3.connect(path)
        conn.execute("PRAGMA journal_mode = WAL")
        conn.execute("PRAGMA foreign_keys = ON")
        conn.execute("PRAGMA synchronous = NORMAL")
        return DB(conn, "sqlite")

    if url.startswith(("postgresql://", "postgres://")):
        try:
            import psycopg
        except ImportError:
            raise SystemExit(
                "[!] PostgreSQL URL given but psycopg is not installed.\n"
                "    pip install 'psycopg[binary]'")
        problem = pg_url_problem(url)
        if problem:
            raise SystemExit("[!] " + problem)
        # A bare 'postgresql://' is valid and intentional: libpq then reads
        # PGHOST/PGPORT/PGUSER/PGPASSWORD/PGDATABASE from the environment, which
        # is the only way to pass a password containing URL-reserved characters
        # without encoding it.
        return DB(psycopg.connect(url), "postgres")

    raise SystemExit(f"[!] unsupported CK_DB_URL: {url!r}\n"
                     "    use sqlite:///path/to.db or postgresql://user:pw@host:5432/db")


def describe(url=None):
    """A log-safe rendering of the target. Never returns the password."""
    url = url or os.environ.get("CK_DB_URL") or DEFAULT_URL
    if url.rstrip("/") in ("postgresql:", "postgres:"):
        # bare URL: the real target lives in the libpq environment variables
        return ("postgresql://{u}:***@{h}:{p}/{d}".format(
            u=os.environ.get("PGUSER", "?"), h=os.environ.get("PGHOST", "?"),
            p=os.environ.get("PGPORT", "5432"), d=os.environ.get("PGDATABASE", "?")))
    return re.sub(r"//([^:/@]+):[^@]*@", r"//\1:***@", url)   # redact password
